repos:
  - repo: local
    hooks:
      - id: create markdown file
        name: create markdown file
        entry: python
        args: ["main.py"]
        language: python
        types: [python]
        pass_filenames: true