repos:
  - repo: local
    hooks:
      - id: create markdown file
        name: create markdown file
        entry: bash -c "python main.py"
        # entry: python
        # args: ["main.py"]
        language: system
        # language: python
        types: [python]
        pass_filenames: false